import { randomUUID } from 'node:crypto';
import { DocumentParser } from './document-parser.js';
import { ChunkService } from './chunk-service.js';
import { EmbeddingService } from './embedding-service.js';
import { MetadataExtractor } from './metadata-extractor.js';
import { validateKnowledgeGeneratorInput } from './knowledge-generator.validation.js';
import type { KnowledgeContentType, KnowledgeGeneratorInputDto, KnowledgeDocumentDto, KnowledgeGeneratorResponseDto } from './knowledge-generator.dto.js';
import type { KnowledgeRepository } from './knowledge-generator.types.js';

interface AutoGeneratedContent {
  title: string;
  content: string;
  metadata: Record<string, unknown>;
}

export class KnowledgeGeneratorService {
  constructor(
    private readonly repository: KnowledgeRepository,
    private readonly parser: DocumentParser = new DocumentParser(),
    private readonly chunkService: ChunkService = new ChunkService(),
    private readonly embeddingService: EmbeddingService = new EmbeddingService(),
    private readonly metadataExtractor: MetadataExtractor = new MetadataExtractor()
  ) {}

  private autoGenerateFAQ(industry: string, requirements: string[]): AutoGeneratedContent[] {
    const questions = requirements.length > 0
      ? requirements.map((req, i) => ({
          question: `Q${i + 1}: ${req}?`,
          answer: `A${i + 1}: The standard ${industry} procedure for "${req}" involves following established guidelines and best practices. Refer to the relevant department for specific details.`
        }))
      : [
          { question: `What is ${industry || 'our'} standard onboarding process?`, answer: `The standard onboarding process for ${industry || 'our organization'} includes orientation, training, and integration into the team workflow.` },
          { question: `How do I submit a ${industry || 'departmental'} request?`, answer: `Submit requests through the designated ${industry || 'internal'} portal with all required documentation attached.` },
          { question: `What are the ${industry || 'key'} compliance requirements?`, answer: `${industry || 'All'} compliance requirements are documented in the employee handbook and regulatory guidelines.` }
        ];

    return [{
      title: `${industry || 'General'} FAQ`,
      content: JSON.stringify(questions, null, 2),
      metadata: { type: 'faq', questions: questions.length, industry }
    }];
  }

  private autoGenerateSOP(industry: string, requirements: string[]): AutoGeneratedContent[] {
    const steps = requirements.length > 0
      ? requirements.map((req, i) => ({
          step: i + 1,
          action: `Handle ${req}`,
          description: `Follow the standard ${industry} operating procedure for ${req}. Ensure all checks are completed before proceeding.`,
          owner: `${industry} Operations Team`,
          duration: 'As per standard timeline'
        }))
      : [
          { step: 1, action: 'Initial Assessment', description: 'Evaluate the request or task against standard criteria.', owner: 'Team Lead', duration: '1 hour' },
          { step: 2, action: 'Documentation Review', description: 'Review all relevant documentation and records.', owner: 'Documentation Team', duration: '2 hours' },
          { step: 3, action: 'Approval Process', description: 'Submit for approval through the chain of command.', owner: 'Manager', duration: '1 day' },
          { step: 4, action: 'Implementation', description: 'Execute the approved plan with proper tracking.', owner: 'Operations Team', duration: 'Variable' },
          { step: 5, action: 'Quality Check', description: 'Verify the implementation meets quality standards.', owner: 'Quality Assurance', duration: '2 hours' }
        ];

    return [{
      title: `${industry || 'General'} Standard Operating Procedure`,
      content: JSON.stringify({ procedureTitle: `${industry || 'Standard'} Operating Procedure`, steps }, null, 2),
      metadata: { type: 'sop', steps: steps.length, industry }
    }];
  }

  private autoGenerateDocumentation(industry: string, requirements: string[]): AutoGeneratedContent[] {
    const sections = requirements.length > 0
      ? requirements.map((req, i) => ({
          section: i + 1,
          heading: req,
          body: `This section documents the ${industry} approach to ${req}. All team members should familiarize themselves with the content and update as processes evolve.`,
          lastUpdated: new Date().toISOString().split('T')[0]
        }))
      : [
          { section: 1, heading: 'Overview', body: `This document provides internal documentation for ${industry || 'the organization'}.`, lastUpdated: new Date().toISOString().split('T')[0] },
          { section: 2, heading: 'Architecture', body: 'Describe the system architecture, components, and their interactions.', lastUpdated: new Date().toISOString().split('T')[0] },
          { section: 3, heading: 'Configuration', body: 'Outline the configuration parameters and environment setup.', lastUpdated: new Date().toISOString().split('T')[0] },
          { section: 4, heading: 'Deployment', body: 'Step-by-step deployment instructions for production environments.', lastUpdated: new Date().toISOString().split('T')[0] },
          { section: 5, heading: 'Maintenance', body: 'Routine maintenance tasks, schedules, and escalation procedures.', lastUpdated: new Date().toISOString().split('T')[0] }
        ];

    return [{
      title: `${industry || 'General'} Internal Documentation`,
      content: JSON.stringify({ documentTitle: `${industry || 'Internal'} Documentation`, sections }, null, 2),
      metadata: { type: 'documentation', sections: sections.length, industry }
    }];
  }

  private autoGenerateAIContext(industry: string, requirements: string[]): AutoGeneratedContent[] {
    const contexts = requirements.length > 0
      ? requirements.map((req, i) => ({
          contextId: `ctx_${i + 1}`,
          domain: req,
          description: `AI context for ${industry} domain: ${req}. This provides the necessary background for AI agents to operate effectively.`,
          relevantEntities: [industry, req, `${industry}_agent`],
          constraints: ['Follow company policies', 'Adhere to regulatory requirements', 'Maintain data privacy']
        }))
      : [
          { contextId: 'ctx_1', domain: `${industry || 'General'} Operations`, description: `Core operational context for ${industry || 'the organization'}. Defines how AI agents interact with standard processes.`, relevantEntities: [industry || 'organization', 'operations', 'agent'], constraints: ['Data privacy', 'Compliance', 'Accuracy'] },
          { contextId: 'ctx_2', domain: 'Knowledge Management', description: 'Context for retrieving and synthesizing knowledge from the knowledge base.', relevantEntities: ['knowledge_base', 'documents', 'embeddings'], constraints: ['Source attribution', 'Confidence scoring'] },
          { contextId: 'ctx_3', domain: 'Communication', description: 'Guidelines for AI agent communication style and tone.', relevantEntities: ['communication', 'template', 'response'], constraints: ['Professional tone', 'Clarity', 'Conciseness'] }
        ];

    return [{
      title: `${industry || 'General'} AI Context`,
      content: JSON.stringify({ aiContext: `${industry} AI Agent Context`, contexts }, null, 2),
      metadata: { type: 'ai_context', contexts: contexts.length, industry }
    }];
  }

  private autoGeneratePromptContext(industry: string, requirements: string[]): AutoGeneratedContent[] {
    const prompts = requirements.length > 0
      ? requirements.map((req, i) => ({
          promptId: `prompt_${i + 1}`,
          useCase: req,
          systemPrompt: `You are an AI assistant specialized in ${industry} with expertise in ${req}. Provide accurate, helpful responses based on the knowledge base.`,
          userPromptTemplate: `Regarding ${req} in ${industry}, please provide detailed information based on our internal knowledge.`,
          constraints: ['Base responses on provided knowledge only', 'Do not invent information', 'Mark uncertainty explicitly']
        }))
      : [
          { promptId: 'prompt_1', useCase: `${industry || 'General'} Inquiry`, systemPrompt: `You are an AI assistant for ${industry || 'the organization'}. Answer questions based on the internal knowledge base.`, userPromptTemplate: 'Answer the following question based on our knowledge base: {query}', constraints: ['Factual accuracy', 'Knowledge base grounding'] },
          { promptId: 'prompt_2', useCase: 'Document Summarization', systemPrompt: 'You are a document summarization assistant. Extract key points from documents.', userPromptTemplate: 'Summarize the following document: {content}', constraints: ['Preserve key facts', 'Maintain context'] },
          { promptId: 'prompt_3', useCase: 'Process Guidance', systemPrompt: 'You are a process guidance assistant. Help users navigate standard operating procedures.', userPromptTemplate: 'Guide me through the process for: {processName}', constraints: ['Step-by-step clarity', 'Reference SOP documents'] }
        ];

    return [{
      title: `${industry || 'General'} Prompt Context`,
      content: JSON.stringify({ promptLibrary: `${industry} Prompt Context`, prompts }, null, 2),
      metadata: { type: 'prompt_context', prompts: prompts.length, industry }
    }];
  }

  private autoGenerateTrainingMaterial(industry: string, requirements: string[]): AutoGeneratedContent[] {
    const modules = requirements.length > 0
      ? requirements.map((req, i) => ({
          module: i + 1,
          title: req,
          objective: `Understand and apply ${industry} best practices for ${req}.`,
          content: `Training module covering ${req} in the context of ${industry}. Includes theoretical background, practical examples, and assessment criteria.`,
          duration: '30 minutes',
          assessmentCriteria: [`Demonstrate understanding of ${req}`, `Apply ${industry} standards to ${req}`, `Complete practical exercise on ${req}`]
        }))
      : [
          { module: 1, title: `${industry || 'Organization'} Fundamentals`, objective: `Understand the core principles of ${industry || 'the organization'}.`, content: `Introduction to ${industry || 'the organization'}, its structure, values, and operational framework.`, duration: '45 minutes', assessmentCriteria: ['Recall key principles', 'Identify organizational structure'] },
          { module: 2, title: 'Tools and Systems', objective: 'Learn to use essential tools and systems.', content: 'Hands-on training for the tools used in daily operations.', duration: '60 minutes', assessmentCriteria: ['Navigate tools proficiently', 'Complete assigned tasks'] },
          { module: 3, title: 'Compliance and Standards', objective: 'Understand compliance requirements and quality standards.', content: 'Overview of regulatory requirements, internal policies, and quality benchmarks.', duration: '30 minutes', assessmentCriteria: ['Identify compliance requirements', 'Apply standards correctly'] }
        ];

    return [{
      title: `${industry || 'General'} Training Material`,
      content: JSON.stringify({ trainingProgram: `${industry || 'General'} Training`, modules }, null, 2),
      metadata: { type: 'training_material', modules: modules.length, industry }
    }];
  }

  private autoGenerateContent(
    contentType: KnowledgeContentType,
    industry: string,
    requirements: string[]
  ): AutoGeneratedContent[] {
    const map: Record<KnowledgeContentType, (industry: string, requirements: string[]) => AutoGeneratedContent[]> = {
      faq: this.autoGenerateFAQ.bind(this),
      sop: this.autoGenerateSOP.bind(this),
      documentation: this.autoGenerateDocumentation.bind(this),
      ai_context: this.autoGenerateAIContext.bind(this),
      prompt_context: this.autoGeneratePromptContext.bind(this),
      training_material: this.autoGenerateTrainingMaterial.bind(this)
    };

    const generator = map[contentType];
    if (!generator) {
      return [];
    }

    return generator(industry, requirements);
  }

  async generate(input: KnowledgeGeneratorInputDto): Promise<KnowledgeGeneratorResponseDto> {
    const validated = validateKnowledgeGeneratorInput({
      organizationId: input.organizationId,
      content: input.content,
      files: input.files,
      title: input.title
    });

    if (input.autoGenerate && input.contentType) {
      const industry = validated.title !== 'Knowledge Base' ? validated.title : '';
      const requirements = input.requirements ?? [];
      const autoGenerated = this.autoGenerateContent(input.contentType, industry, requirements);

      const documents: KnowledgeDocumentDto[] = autoGenerated.map((gen) => {
        const parsed = this.parser.parse(gen.content, gen.title);
        const chunks = this.chunkService.chunk(parsed.text);
        const metadata = this.metadataExtractor.extract(parsed.text, 'auto_generated');
        return {
          id: randomUUID(),
          title: gen.title,
          content: parsed.text,
          sourceType: 'auto_generated',
          sourceUrl: input.sourceUrl,
          metadata: { ...metadata, ...gen.metadata, chunks: chunks.length },
          tags: Array.isArray(metadata.tags) ? [...metadata.tags as string[]].concat(input.contentType ?? []) : [input.contentType].filter(Boolean) as string[],
          language: metadata.language as string,
          summary: parsed.summary
        };
      });

      const saved = await this.repository.save({
        id: randomUUID(),
        organizationId: validated.organizationId,
        title: `${validated.title} ${input.contentType.replace('_', ' ').replace(/\b\w/g, (c) => c.toUpperCase())}`,
        documents,
        tags: [input.contentType, ...new Set(documents.flatMap((document) => document.tags))],
        metadata: { generatedBy: 'KnowledgeGeneratorService', autoGenerated: true, contentType: input.contentType, requirements: input.requirements ?? [] },
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      });

      return {
        id: saved.id,
        organizationId: saved.organizationId,
        title: saved.title,
        documents: saved.documents as KnowledgeDocumentDto[],
        tags: saved.tags,
        metadata: saved.metadata,
        status: 'active',
        createdAt: saved.createdAt,
        updatedAt: saved.updatedAt
      };
    }

    const sources = [
      ...(validated.content ? [{ title: validated.title, content: validated.content, sourceType: input.sourceType ?? 'text' }] : []),
      ...validated.files.map((file) => ({ title: file.name, content: file.content ?? '', sourceType: file.mimeType ?? 'file' }))
    ];

    const documents: KnowledgeDocumentDto[] = [];
    for (const source of sources) {
      const parsed = this.parser.parse(source.content, source.title);
      const chunks = this.chunkService.chunk(parsed.text);
      const embeddings = await Promise.all(chunks.map((chunk) => this.embeddingService.embed(chunk)));
      const metadata = this.metadataExtractor.extract(parsed.text, source.sourceType);
      documents.push({
        id: randomUUID(),
        title: source.title,
        content: parsed.text,
        sourceType: source.sourceType,
        sourceUrl: input.sourceUrl,
        metadata: { ...metadata, chunks: chunks.length, embeddingSize: embeddings[0]?.length ?? 0 },
        tags: Array.isArray(metadata.tags) ? metadata.tags as string[] : [],
        language: metadata.language as string,
        summary: parsed.summary
      });
    }

    const saved = await this.repository.save({
      id: randomUUID(),
      organizationId: validated.organizationId,
      title: validated.title,
      documents,
      tags: [...new Set(documents.flatMap((document) => document.tags))],
      metadata: { generatedBy: 'KnowledgeGeneratorService', requirements: input.requirements ?? [] },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    });

    return {
      id: saved.id,
      organizationId: saved.organizationId,
      title: saved.title,
      documents: saved.documents as KnowledgeDocumentDto[],
      tags: saved.tags,
      metadata: saved.metadata,
      status: 'active',
      createdAt: saved.createdAt,
      updatedAt: saved.updatedAt
    };
  }
}
