import 'dotenv/config';
import express from 'express';
import { authenticate, requireRole } from '../middleware/auth.middleware.js';
import { importWorkflowsHandler } from './admin/import-workflows.js';
import { businessAnalyzerHandler } from './ai-factory/business-analyzer.js';
import { employeeGeneratorHandler } from './ai-factory/employee-generator.js';
import { agentGeneratorHandler } from './ai-factory/agent-generator.js';
import { promptGeneratorHandler } from './ai-factory/prompt-generator.js';
import { knowledgeGeneratorHandler } from './ai-factory/knowledge-generator.js';
import { deploymentManagerHandler } from './ai-factory/deployment-manager.js';
import { workflowAnalyzerHandler } from './ai-factory/workflow-analyzer.js';
import { templateSearchHandler } from './ai-factory/template-search.js';
import { workflowGenerateHandler } from './ai-factory/workflow-generate.js';
import { aiProviderHealthHandler } from './ai-provider.js';
import { supabaseHealthHandler } from './supabase.js';
import { aiFactoryHealthHandler, promptEngineHealthHandler, workflowGeneratorHealthHandler, businessAnalyzerHealthHandler, employeeGeneratorHealthHandler, agentGeneratorHealthHandler, workflowAnalyzerHealthHandler, templateSearchHealthHandler } from './health.js';
import healthCheckRoutes from './health-check.js';
import { activateN8nWorkflowHandler, deactivateN8nWorkflowHandler, deleteN8nWorkflowHandler, deployN8nWorkflowHandler, executeN8nWorkflowHandler, getN8nWorkflowHandler, n8nHealthHandler, syncN8nCredentialsHandler, updateN8nWorkflowHandler } from './n8n.js';
import { marketplacePublishHandler, marketplaceRecommendHandler } from './marketplace.js';
import { templateLibraryScanHandler, templateLibraryStatsHandler } from './template-library.js';
import { qaEngineHandler } from './qa-engine.js';
import { solutionArchitectHandler } from './solution-architect.js';
import authRoutes from './auth/index.js';
import billingRoutes from './billing/index.js';
import dashboardRoutes from './dashboard/index.js';
import storeRoutes from './store/index.js';
import auditRoutes from './audit/index.js';
import deployRoutes from './deploy/index.js';
import aiOrchestratorRoutes from './ai-orchestrator/index.js';
import promptRoutes from './prompts/index.js';
import aiMemoryRoutes from './ai-memory/index.js';
import aiPlaygroundRoutes from './ai-playground/index.js';
import seoRoutes from './seo/index.js';
import geoRoutes from './geo/index.js';
import aeoRoutes from './aeo/index.js';
import contentStudioRoutes from './content-studio/index.js';
import blogRoutes from './blog/index.js';
import marketingRoutes from './marketing/index.js';
import devopsRoutes from './devops/index.js';
import deploymentRoutes from './deployments/index.js';
import provisioningRoutes from './provisioning/index.js';
import organizationRoutes from './organizations/index.js';
import apiKeyRoutes from './api-keys/index.js';
import securityRoutes from './security/index.js';
import credentialRoutes from './credentials/index.js';
import monitoringRoutes from './monitoring/index.js';
import notificationRoutes from './notifications/index.js';
import backupRoutes from './backups/index.js';
import licenseRoutes from './licenses/index.js';
import featureFlagRoutes from './feature-flags/index.js';
import launchCenterRoutes from './launch-center/index.js';
import importExportRoutes from './import-export/index.js';
import { securityMiddleware, corsMiddleware, globalRateLimit, requestIdMiddleware, errorHandler } from '../middleware/security.middleware.js';
import { optionalAuth } from '../middleware/auth.middleware.js';
import { whitelabel } from '../middleware/whitelabel.middleware.js';

const app = express();

app.use(whitelabel);
app.use(securityMiddleware);
app.use(corsMiddleware);
app.use(globalRateLimit);
app.use(requestIdMiddleware);
app.use(optionalAuth);

app.post('/api/billing/webhook', express.raw({ type: 'application/json' }));
app.use(express.json());

app.use('/healthz', healthCheckRoutes);
app.use('/api/auth', authRoutes);
app.use('/api/billing', billingRoutes);
app.use('/api/dashboard', authenticate, dashboardRoutes);
app.use('/api/store', authenticate, storeRoutes);
app.use('/api/audit', authenticate, auditRoutes);
app.use('/api/deploy', authenticate, deployRoutes);
app.use('/api/ai', authenticate, aiOrchestratorRoutes);
app.use('/api/prompts', authenticate, promptRoutes);
app.use('/api/ai-memory', authenticate, aiMemoryRoutes);
app.use('/api/playground', authenticate, aiPlaygroundRoutes);
app.use('/api/seo', authenticate, seoRoutes);
app.use('/api/geo', authenticate, geoRoutes);
app.use('/api/aeo', authenticate, aeoRoutes);
app.use('/api/content', authenticate, contentStudioRoutes);
app.use('/api/blog', authenticate, blogRoutes);
app.use('/api/marketing', authenticate, marketingRoutes);
app.use('/api/devops', authenticate, devopsRoutes);
app.use('/api/deployments', authenticate, deploymentRoutes);
app.use('/api/provisioning', authenticate, provisioningRoutes);
app.use('/api/organizations', authenticate, organizationRoutes);
app.use('/api/api-keys', authenticate, apiKeyRoutes);
app.use('/api/security', authenticate, securityRoutes);
app.use('/api/credentials', authenticate, credentialRoutes);
app.use('/api/monitoring', authenticate, monitoringRoutes);
app.use('/api/notifications', authenticate, notificationRoutes);
app.use('/api/backups', authenticate, backupRoutes);
app.use('/api/licenses', authenticate, licenseRoutes);
app.use('/api/feature-flags', authenticate, featureFlagRoutes);
app.use('/api/launch-center', authenticate, launchCenterRoutes);
app.use('/api/import-export', authenticate, importExportRoutes);

const requireAdmin = requireRole('Super Admin', 'Organization Admin');
app.post('/api/admin/import-workflows', authenticate, requireAdmin, importWorkflowsHandler);
app.post('/api/ai-factory/business-analyzer', authenticate, businessAnalyzerHandler);
app.post('/api/ai-factory/employee-generator', authenticate, employeeGeneratorHandler);
app.post('/api/ai-factory/agent-generator', authenticate, agentGeneratorHandler);
app.post('/api/ai-factory/prompt-generator', authenticate, promptGeneratorHandler);
app.post('/api/ai-factory/knowledge-generator', authenticate, knowledgeGeneratorHandler);
app.post('/api/ai-factory/deploy', authenticate, deploymentManagerHandler);
app.post('/api/workflow-analyzer', authenticate, workflowAnalyzerHandler);
app.post('/api/template-search', authenticate, templateSearchHandler);
app.post('/api/workflow-generate', authenticate, workflowGenerateHandler);
app.post('/api/qa/evaluate', authenticate, qaEngineHandler);
app.post('/api/solution-architect/design', authenticate, solutionArchitectHandler);
app.post('/api/marketplace/publish', authenticate, marketplacePublishHandler);
app.post('/api/marketplace/recommend', authenticate, marketplaceRecommendHandler);
app.post('/api/template-library/scan', authenticate, templateLibraryScanHandler);
app.get('/api/template-library/stats', authenticate, templateLibraryStatsHandler);
app.get('/api/health', aiFactoryHealthHandler);
app.get('/api/health/ai-provider', aiProviderHealthHandler);
app.get('/api/health/supabase', supabaseHealthHandler);
app.get('/api/health/prompt-engine', promptEngineHealthHandler);
app.get('/api/health/workflow-generator', workflowGeneratorHealthHandler);
app.get('/api/health/business-analyzer', businessAnalyzerHealthHandler);
app.get('/api/health/employee-generator', employeeGeneratorHealthHandler);
app.get('/api/health/agent-generator', agentGeneratorHealthHandler);
app.get('/api/health/workflow-analyzer', workflowAnalyzerHealthHandler);
app.get('/api/health/template-search', templateSearchHealthHandler);
app.post('/api/n8n/deploy', authenticate, deployN8nWorkflowHandler);
app.post('/api/n8n/update/:id', authenticate, updateN8nWorkflowHandler);
app.post('/api/n8n/activate/:id', authenticate, activateN8nWorkflowHandler);
app.post('/api/n8n/deactivate/:id', authenticate, deactivateN8nWorkflowHandler);
app.post('/api/n8n/execute/:id', authenticate, executeN8nWorkflowHandler);
app.delete('/api/n8n/workflow/:id', authenticate, deleteN8nWorkflowHandler);
app.get('/api/n8n/workflow/:id', authenticate, getN8nWorkflowHandler);
app.get('/api/n8n/health', n8nHealthHandler);
app.post('/api/n8n/credentials/sync', authenticate, syncN8nCredentialsHandler);

app.use(errorHandler);

function validateStartupConfig(): void {
  const required = ['JWT_SECRET', 'ENCRYPTION_KEY', 'SUPABASE_URL'];
  const missing = required.filter((name) => !process.env[name]);
  if (missing.length > 0) {
    console.warn(`Startup validation warning: missing ${missing.join(', ')}`);
  }
}

validateStartupConfig();

const port = Number(process.env.PORT ?? 3000);
app.listen(port, () => {
  console.log(`BUILDAGENT server listening on port ${port}`);
});
