import 'dotenv/config';
import express from 'express';
import { requireRole } from '../middleware/auth.middleware.js';
import { importWorkflowsHandler } from './admin/import-workflows.js';
import { businessAnalyzerHandler } from './ai-factory/business-analyzer.js';
import { employeeGeneratorHandler } from './ai-factory/employee-generator.js';
import { agentGeneratorHandler } from './ai-factory/agent-generator.js';
import { promptGeneratorHandler } from './ai-factory/prompt-generator.js';
import { knowledgeGeneratorHandler } from './ai-factory/knowledge-generator.js';
import { deploymentManagerHandler } from './ai-factory/deployment-manager.js';
import { workflowAnalyzerHandler } from './ai-factory/workflow-analyzer.js';
import { templateSearchHandler } from './ai-factory/template-search.js';
import { workflowGenerateHandler } from './ai-factory/workflow-generate.js';
import { aiProviderHealthHandler } from './ai-provider.js';
import { supabaseHealthHandler } from './supabase.js';
import { aiFactoryHealthHandler, promptEngineHealthHandler, workflowGeneratorHealthHandler, businessAnalyzerHealthHandler, employeeGeneratorHealthHandler, agentGeneratorHealthHandler, workflowAnalyzerHealthHandler, templateSearchHealthHandler } from './health.js';
import { activateN8nWorkflowHandler, deactivateN8nWorkflowHandler, deleteN8nWorkflowHandler, deployN8nWorkflowHandler, executeN8nWorkflowHandler, getN8nWorkflowHandler, n8nHealthHandler, syncN8nCredentialsHandler, updateN8nWorkflowHandler } from './n8n.js';
import { marketplacePublishHandler, marketplaceRecommendHandler } from './marketplace.js';
import { templateLibraryScanHandler, templateLibraryStatsHandler } from './template-library.js';
import { qaEngineHandler } from './qa-engine.js';
import { solutionArchitectHandler } from './solution-architect.js';
import authRoutes from './auth/index.js';
import billingRoutes from './billing/index.js';
import dashboardRoutes from './dashboard/index.js';
import storeRoutes from './store/index.js';
import auditRoutes from './audit/index.js';
import deployRoutes from './deploy/index.js';
import aiOrchestratorRoutes from './ai-orchestrator/index.js';
import promptRoutes from './prompts/index.js';
import aiMemoryRoutes from './ai-memory/index.js';
import aiPlaygroundRoutes from './ai-playground/index.js';
import seoRoutes from './seo/index.js';
import geoRoutes from './geo/index.js';
import aeoRoutes from './aeo/index.js';
import contentStudioRoutes from './content-studio/index.js';
import blogRoutes from './blog/index.js';
import marketingRoutes from './marketing/index.js';
import devopsRoutes from './devops/index.js';
import deploymentRoutes from './deployments/index.js';
import provisioningRoutes from './provisioning/index.js';
import organizationRoutes from './organizations/index.js';
import apiKeyRoutes from './api-keys/index.js';
import securityRoutes from './security/index.js';
import credentialRoutes from './credentials/index.js';
import monitoringRoutes from './monitoring/index.js';
import notificationRoutes from './notifications/index.js';
import backupRoutes from './backups/index.js';
import licenseRoutes from './licenses/index.js';
import featureFlagRoutes from './feature-flags/index.js';
import launchCenterRoutes from './launch-center/index.js';
import importExportRoutes from './import-export/index.js';
import { securityMiddleware, corsMiddleware, globalRateLimit, requestIdMiddleware, errorHandler } from '../middleware/security.middleware.js';
import { optionalAuth } from '../middleware/auth.middleware.js';
import { whitelabel } from '../middleware/whitelabel.middleware.js';

const app = express();

app.use(whitelabel);
app.use(securityMiddleware);
app.use(corsMiddleware);
app.use(globalRateLimit);
app.use(requestIdMiddleware);
app.use(optionalAuth);

app.post('/api/billing/webhook', express.raw({ type: 'application/json' }));
app.use(express.json());

app.use('/api/auth', authRoutes);
app.use('/api/billing', billingRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use('/api/store', storeRoutes);
app.use('/api/audit', auditRoutes);
app.use('/api/deploy', deployRoutes);
app.use('/api/ai', aiOrchestratorRoutes);
app.use('/api/prompts', promptRoutes);
app.use('/api/ai-memory', aiMemoryRoutes);
app.use('/api/playground', aiPlaygroundRoutes);
app.use('/api/seo', seoRoutes);
app.use('/api/geo', geoRoutes);
app.use('/api/aeo', aeoRoutes);
app.use('/api/content', contentStudioRoutes);
app.use('/api/blog', blogRoutes);
app.use('/api/marketing', marketingRoutes);
app.use('/api/devops', devopsRoutes);
app.use('/api/deployments', deploymentRoutes);
app.use('/api/provisioning', provisioningRoutes);
app.use('/api/organizations', organizationRoutes);
app.use('/api/api-keys', apiKeyRoutes);
app.use('/api/security', securityRoutes);
app.use('/api/credentials', credentialRoutes);
app.use('/api/monitoring', monitoringRoutes);
app.use('/api/notifications', notificationRoutes);
app.use('/api/backups', backupRoutes);
app.use('/api/licenses', licenseRoutes);
app.use('/api/feature-flags', featureFlagRoutes);
app.use('/api/launch-center', launchCenterRoutes);
app.use('/api/import-export', importExportRoutes);

const requireAdmin = requireRole('Super Admin', 'Organization Admin');
app.post('/api/admin/import-workflows', requireAdmin, importWorkflowsHandler);
app.post('/api/ai-factory/business-analyzer', businessAnalyzerHandler);
app.post('/api/ai-factory/employee-generator', employeeGeneratorHandler);
app.post('/api/ai-factory/agent-generator', agentGeneratorHandler);
app.post('/api/ai-factory/prompt-generator', promptGeneratorHandler);
app.post('/api/ai-factory/knowledge-generator', knowledgeGeneratorHandler);
app.post('/api/ai-factory/deploy', deploymentManagerHandler);
app.post('/api/workflow-analyzer', workflowAnalyzerHandler);
app.post('/api/template-search', templateSearchHandler);
app.post('/api/workflow-generate', workflowGenerateHandler);
app.post('/api/qa/evaluate', qaEngineHandler);
app.post('/api/solution-architect/design', solutionArchitectHandler);
app.post('/api/marketplace/publish', marketplacePublishHandler);
app.post('/api/marketplace/recommend', marketplaceRecommendHandler);
app.post('/api/template-library/scan', templateLibraryScanHandler);
app.get('/api/template-library/stats', templateLibraryStatsHandler);
app.get('/api/health', aiFactoryHealthHandler);
app.get('/api/health/ai-provider', aiProviderHealthHandler);
app.get('/api/health/supabase', supabaseHealthHandler);
app.get('/api/health/prompt-engine', promptEngineHealthHandler);
app.get('/api/health/workflow-generator', workflowGeneratorHealthHandler);
app.get('/api/health/business-analyzer', businessAnalyzerHealthHandler);
app.get('/api/health/employee-generator', employeeGeneratorHealthHandler);
app.get('/api/health/agent-generator', agentGeneratorHealthHandler);
app.get('/api/health/workflow-analyzer', workflowAnalyzerHealthHandler);
app.get('/api/health/template-search', templateSearchHealthHandler);
app.post('/api/n8n/deploy', deployN8nWorkflowHandler);
app.post('/api/n8n/update/:id', updateN8nWorkflowHandler);
app.post('/api/n8n/activate/:id', activateN8nWorkflowHandler);
app.post('/api/n8n/deactivate/:id', deactivateN8nWorkflowHandler);
app.post('/api/n8n/execute/:id', executeN8nWorkflowHandler);
app.delete('/api/n8n/workflow/:id', deleteN8nWorkflowHandler);
app.get('/api/n8n/workflow/:id', getN8nWorkflowHandler);
app.get('/api/n8n/health', n8nHealthHandler);
app.post('/api/n8n/credentials/sync', syncN8nCredentialsHandler);

app.use(errorHandler);

const port = Number(process.env.PORT ?? 3000);
app.listen(port, () => {
  console.log(`BUILDAGENT server listening on port ${port}`);
});
